### ISSUE TITLE
DOC/Demo App -  webcredentials not needed

### ISSUE THREAD

**Issue by asr-enid** [eunid/netid-sdk-ios#118]
The README states that webcredentials entitelment must be added in order to use UniversalLinks - I don't think this is the case? Its part of the demo apps too, but this is a distinct feature of domain association to my understanding

**Comment by tbachmor-letsdev** [comment]
The webcredentials entitlement ensures, that things like logins/password can be shared amongst apps/web-sites via the use of the iCloud-keychain. So, technically universal links will work without this feature but would force the user to reenter his credentials.
Do you want us to remove this?

**Comment by asr-enid** [comment]
> The webcredentials entitlement ensures, that things like logins/password can be shared amongst apps/web-sites via the use of the iCloud-keychain. So, technically universal links will work without this feature but would force the user to reenter his credentials.

As far as I understand webcredentials its about username/password shared _between an app and the website of the same developer_, I don't see how that has any relation to the Demo Application or generally the functionality of the SDK (The Doc currently states that the entitlement is necessary I think). 

The user never enters a username/password on the redirect domain (e.g. eunid.github.io in our demo case, for which the entitlement would be valid) nor in the Demo App - the SDK is all about not having to do that as an app that logs in a users using one of the login flows for example. The Demo App also does not try to use this API (iOS side)

If I'm missing something here let me know.

**Comment by asr-enid** [comment]
>  You must add your domain for webcredentials as well as for applinks to make it work both in app2web and app2app scenarios.

In relation to doc - I don't think anything would change if the webcredentials entitelment is removed in the Demo App

**Comment by tbachmor-letsdev** [comment]
You are right, it is not necessary, we updated the project settings and documentation accordingly.
